spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: hotel
    password: hotel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

security:
  jwt:
    secret: change-me-please-32chars-min
    expirationSeconds: 3600

